# Generated by Django 3.2.5 on 2021-07-31 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_rename_skiils_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporateField', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_field', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
